name: bench_simulator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  logger: ^1.2.2
  path: ^1.8.0
  bench_communication:
    path: ../bench_communication

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
